config/routes.rb
Guestbook::Application.routes.draw do
  resources :events do
    resources :guests
  end
  get 'events/angular' => 'events#angular', as: :angular

  root 'events#index'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :guests, dependent: :destroy, inverse_of: :event
  validates_presence_of :name
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :event, inverse_of: :guests
  validates_inclusion_of :designation, :in => %w[Mr Ms Mrs Dr]
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates_presence_of :email
  validates_uniqueness_of :email, scope: :event
  validates :name, :presence => true

  before_validation do
    self.phone = phone.to_s.gsub(/\D/, '').to_i
  end

  def status
    read_attribute(:designation).to_sym
  end

  def status= (value)
    write_attribute(:designation, value.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def angular
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @events.each do |event|
      event.description = event.description.truncate( 350, { :separator => ' ', :omission => ' ...' } )
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.json { render :json => @event.to_json(include: :guests ) }
      format.html { render :html => @event }
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    flash[:error] = 'Event was deleted'
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
      format.js   { render :nothing => true }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description)
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :get_event
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  def get_event
    @event = Event.find(params[:event_id])
  end

  def index
    respond_to do |format|
      format.json { render :json => @event.guests.to_json }
    end
  end

  def show
    respond_to do |format|
      format.json { render :json => @guest.to_json }
    end
  end

  # GET /guests/new
  def new
    @guest = @event.guests.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = @event.guests.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @event, notice: 'Guest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @event, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to @event }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :email, :phone, :designation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then 'alert alert-info'
      when :success then 'alert alert-success'
      when :error then 'alert alert-error'
      when :alert then 'alert alert-error'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/events/_form.html.erb
<div class="row">
  <%= form_for @event, html: {role: 'form', class: 'col-lg-6'} do |f| %>
      <% if @event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul class="field_with_errors">
              <% @event.errors.full_messages.each do |msg| %>
                  <li> * <%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Enter the name of the event' %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, cols: '30', rows: '10', class: 'form-control', placeholder: 'Please enter a description of the event' %>
      </div>
      <div class="actions">
        <%= f.submit class: 'btn btn-success' %>
      </div>
  <% end %>
</div>

app/views/events/angular.html.erb
<div ng-view="ng-view"></div>

app/views/events/edit.html.erb
<div class="page-header">
  <h1>Editing event</h1>
</div>

<%= render 'form' %>
<br>
<%= link_to 'Show', @event, class: 'btn btn-default' %>
<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/index.html.erb
<div class="page-header">
  <h1>Events</h1>
</div>
<%= link_to 'New Event', new_event_path, class: 'btn btn-success' %>
<br>
<br>
<% if @events.exists? %>
    <div class="row" ng-controller='EventsCtrl'>
      <div class="main-event-li col-md-4" ng-repeat='event in events'>
        <h3>{{ event.name }}</h3>
        <p>{{event.description}}</p>
        <div class="btn-group">
          <%= link_to 'Show', '{{event.url}}', class: 'btn btn-default' %>
          <%= link_to 'Edit', '{{event.url}}/edit', class: 'btn btn-default' %>
          <%= link_to 'Destroy', '{{event.url}}', method: :delete, rel: 'nofollow', data: {confirm: 'Are you sure?'}, class: 'btn btn-danger delete_event' %>
        </div>
        <div class="pull-right">Guests: {{event.guests.length}}</div>
      </div>
    </div>
<% end %>

app/views/events/new.html.erb
<div class="page-header">
  <h1>New event</h1>
</div>

<%= render 'form' %>
<br>
<%= link_to 'Back', events_path, class: 'btn btn-default btn-xs' %>

app/views/events/show.html.erb
<div class="page-header">
  <h1><%= @event.name %></h1>
</div>
<p class="lead">
  <%= @event.description %>
</p>

<%= link_to 'Edit event', edit_event_path(@event), class: 'btn btn-default' %>
<%= link_to 'Back to list', events_path, class: 'btn btn-default' %>

<div class="page-header">
  <h2>Guests</h2>
</div>

<%= link_to 'New Guest', new_event_guest_path(@event), class: 'btn btn-success' %>
<br>
<br>
<% if @event.guests.exists? %>
    <div class="table-responsive">
      <table class="table table-stripped table-bordered table-hover radius">
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th colspan="2"></th>
        </tr>
        </thead>
        <tbody>

        <% @guests = @event.guests.sort {|a,b| b.updated_at <=> a.updated_at } %>
        <% @guests.each do |guest| %>
            <tr>
              <td><%= guest.designation + '. ' + guest.name %></td>
              <td><%= guest.email %></td>
              <td><%= guest.phone %></td>
              <td class="text-center"><%= link_to 'Edit', edit_event_guest_path(@event, guest), class: 'btn btn-default btn-sm' %></td>
              <td class="text-center"><%= link_to 'Delete', [@event, guest], method: :delete, class: 'btn btn-danger btn-sm' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

app/views/guests/_form.html.erb
<div class="row">
  <%= form_for [@event, @guest], html: {role: 'form', class: 'col-lg-6'} do |f| %>
      <% if @guest.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-danger">
                <%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:
            </div>

            <div class="alert alert-danger">
              <ul class="field_with_errors">
                <% @guest.errors.full_messages.each do |msg| %>
                    <li> * <%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter guest's name" %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control', placeholder: "Enter the guest's email" %>
      </div>
      <div class="form-group">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, class: 'form-control', placeholder: "Enter guest's phone number" %>
      </div>
      <div class="form-group">
        <%= f.label :designation %><br>
        <%= f.select(:designation, options_for_select(%w(Mr Ms Mrs Dr)),{}, {class: 'form-control'}) %>
      </div>
      <div class="actions">
        <%= f.submit class: 'btn btn-success' %>
      </div>
  <% end %>
</div>

app/views/guests/edit.html.erb
<div class="page-header">
  <h1>Editing guest</h1>
</div>

<%= render 'form' %>
<br>
<%= link_to 'Back to event', event_path(@event), class: 'btn btn-default btn-xs' %>

app/views/guests/new.html.erb
<div class="page-header">
  <h1>New guest</h1>
</div>

<%= render 'form' %>
<br>
<%= link_to 'Back to event', event_path(@event), class: 'btn btn-default btn-xs' %>

app/views/layouts/_footer.html.erb
<hr>
<div class="text-center">guestbook app for Kiinzel</div>
<hr>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <%= link_to 'Guestbook', root_path, class: 'navbar-brand' %>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <%
           if name == :notice then type = 'info'
           elsif name == :alert then type = 'warning'
           elsif name == :error then type = 'danger'
           else type = 'success'
           end
        %>
        <div class="alert alert-<%= type %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Guestbook' %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<%= render partial: 'layouts/header' %>
<div class="content container">
  <%= render partial: 'layouts/messages', flash: flash %>
  <%= yield %>
  <%= render partial: 'layouts/footer' %>
</div>
</body>
</html>